@AcmeVendingMachine.Server_HostAddress = http://localhost:5136

GET {{AcmeVendingMachine.Server_HostAddress}}/api/Product/Product/
Accept: application/json

###

GET {{AcmeVendingMachine.Server_HostAddress}}/api/VendingMachine/calculateChange?currency=USD&purchaseAmount=1.35&tenderAmount=2
Accept: application/json
###
